name = "QuadratureRules"
uuid = "a08977f5-a20d-4b99-b11f-f5ea535e0575"
authors = ["Michael Kraus"]
version = "0.1.4"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"

[compat]
FastGaussQuadrature = "0.4, 0.5"
GenericLinearAlgebra = "0.2, 0.3"
Polynomials = "1, 2, 3, 4"
julia = "^1.4"

[extras]
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "FastTransforms"]
