name = "QuadratureRules"
uuid = "a08977f5-a20d-4b99-b11f-f5ea535e0575"
authors = ["Michael Kraus"]
version = "0.1.0"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
SpecialPolynomials = "a25cea48-d430-424a-8ee7-0d3ad3742e9e"

[compat]
FastGaussQuadrature = "0.4"
Polynomials = "^1.1.13"
SpecialPolynomials = "0.1"
julia = "1"

[extras]
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "FastTransforms"]
